// Test Phase Stimuli
var testwords = [
    {cue: "<font size = '+2'><b>'Abandon a position'</b></font>",            question: [{prompt: "<font size = '+1'><b>'Abandon a position'</b></font>",              name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "renounce",     word1: "retreat",  word2: "travel",       word3: "yield",        word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "abdicate"      },
    {cue: "<font size = '+2'><b>'To set aside'</b></font>",                  question: [{prompt: "<font size = '+1'><b>'To set aside'</b></font>",                    name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "budget",       word1: "abandon",  word2: "forget",       word3: "store",        word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "allocate"      },
    {cue: "<font size = '+2'><b>'Insulate'</b></font>",                      question: [{prompt: "<font size = '+1'><b>'Insulate'</b></font>",                        name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "cancer",       word1: "walls",    word2: "isolate",      word3: "foam",         word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "asbestos"      },
    {cue: "<font size = '+2'><b>'Holds drinks'</b></font>",                  question: [{prompt: "<font size = '+1'><b>'Holds drinks'</b></font>",                    name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "bottle",       word1: "mug",      word2: "coaster",      word3: "cup",          word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "decanter"      },
    {cue: "<font size = '+2'><b>'To exhaust something'</b></font>",          question: [{prompt: "<font size = '+1'><b>'To exhaust something'</b></font>",            name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "expend",       word1: "exercise", word2: "tire",         word3: "discharge",    word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "deplete"       },
    {cue: "<font size = '+2'><b>'Hold at a certain temperature'</b></font>", question: [{prompt: "<font size = '+1'><b>'Hold at a certain temperature'</b></font>",   name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "nest",         word1: "fridge",   word2: "oven",         word3: "cook",         word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "incubate"      },
    {cue: "<font size = '+2'><b>'To set in motion'</b></font>",              question: [{prompt: "<font size = '+1'><b>'To set in motion'</b></font>",                name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "provoke",      word1: "roll",     word2: "throw",        word3: "commence",     word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "instigate"     },
    {cue: "<font size = '+2'><b>'Something you throw'</b></font>",           question: [{prompt: "<font size = '+1'><b>'Something you throw'</b></font>",             name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "spear",        word1: "ball",     word2: "rock",         word3: "punches",      word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "javelin"       },
    {cue: "<font size = '+2'><b>'Plant-based material'</b></font>",          question: [{prompt: "<font size = '+1'><b>'Plant-based material'</b></font>",            name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "sheets",       word1: "wicker",   word2: "table",        word3: "paper",        word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "linen"         },
    {cue: "<font size = '+2'><b>'Related to navigating'</b></font>",         question: [{prompt: "<font size = '+1'><b>'Related to navigating'</b></font>",           name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "sailing",      word1: "landmark", word2: "gps",          word3: "road",         word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "sextant"       },
    {cue: "<font size = '+2'><b>'A type of fee'</b></font>",                 question: [{prompt: "<font size = '+1'><b>'A type of fee'</b></font>",                   name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "tax",          word1: "parking",  word2: "reservation",  word3: "interest",     word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "tariff"        },
    {cue: "<font size = '+2'><b>'Causes a sedative effect'</b></font>",      question: [{prompt: "<font size = '+1'><b>'Causes a sedative effect'</b></font>",        name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "depressant",   word1: "fatigue",  word2: "tea",          word3: "nap",          word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "tranquilizer"  }
];

var testwords_1 = [
    {cue: "<font size = '+2'><b>'To set aside'</b></font>",                  question: [{prompt: "<font size = '+1'><b>'To set aside'</b></font>",                    name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "<font size='+3'>budget</font>",       word1: "abandon",  word2: "forget",       word3: "store",        word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "allocate"      },
    {cue: "<font size = '+2'><b>'Holds drinks'</b></font>",                  question: [{prompt: "<font size = '+1'><b>'Holds drinks'</b></font>",                    name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "<font size='+3'>bottle</font>",       word1: "mug",      word2: "coaster",      word3: "cup",          word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "decanter"      },
    {cue: "<font size = '+2'><b>'To exhaust something'</b></font>",          question: [{prompt: "<font size = '+1'><b>'To exhaust something'</b></font>",            name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "<font size='+3'>expend</font>",       word1: "exercise", word2: "tire",         word3: "discharge",    word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "deplete"       },
    {cue: "<font size = '+2'><b>'Plant-based material'</b></font>",          question: [{prompt: "<font size = '+1'><b>'Plant-based material'</b></font>",            name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "<font size='+3'>sheets</font>",       word1: "wicker",   word2: "table",        word3: "paper",        word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "linen"         },
    {cue: "<font size = '+2'><b>'Related to navigating'</b></font>",         question: [{prompt: "<font size = '+1'><b>'Related to navigating'</b></font>",           name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "<font size='+3'>sailing</font>",      word1: "landmark", word2: "gps",          word3: "road",         word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "sextant"       },
    {cue: "<font size = '+2'><b>'Causes a sedative effect'</b></font>",      question: [{prompt: "<font size = '+1'><b>'Causes a sedative effect'</b></font>",        name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "<font size='+3'>depressant</font>",   word1: "fatigue",  word2: "tea",          word3: "nap",          word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "tranquilizer"  },
];

var testwords_2 = [
    {cue: "<font size = '+2'><b>'Abandon a position'</b></font>",            question: [{prompt: "<font size = '+1'><b>'Abandon a position'</b></font>",              name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "renounce",     word1: "retreat",  word2: "travel",       word3: "yield",        word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "abdicate"      },
    {cue: "<font size = '+2'><b>'Insulate'</b></font>",                      question: [{prompt: "<font size = '+1'><b>'Insulate'</b></font>",                        name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "cancer",       word1: "walls",    word2: "isolate",      word3: "foam",         word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "asbestos"      },
    {cue: "<font size = '+2'><b>'Hold at a certain temperature'</b></font>", question: [{prompt: "<font size = '+1'><b>'Hold at a certain temperature'</b></font>",   name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "nest",         word1: "fridge",   word2: "oven",         word3: "cook",         word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "incubate"      },
    {cue: "<font size = '+2'><b>'To set in motion'</b></font>",              question: [{prompt: "<font size = '+1'><b>'To set in motion'</b></font>",                name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "provoke",      word1: "roll",     word2: "throw",        word3: "commence",     word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "instigate"     },
    {cue: "<font size = '+2'><b>'Something you throw'</b></font>",           question: [{prompt: "<font size = '+1'><b>'Something you throw'</b></font>",             name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "spear",        word1: "ball",     word2: "rock",         word3: "punches",      word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "javelin"       },
    {cue: "<font size = '+2'><b>'A type of fee'</b></font>",                 question: [{prompt: "<font size = '+1'><b>'A type of fee'</b></font>",                   name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "tax",          word1: "parking",  word2: "reservation",  word3: "interest",     word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "tariff"        },
];