// Test Phase Stimuli
var testwords = [
    {cue: "<b>'Abandon a position'</b>",            question: [{prompt: "<b>'Abandon a position'</b>",              name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "renounce",     word1: "retreat",  word2: "travel",       word3: "yield",        word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "abdicate"      },
    {cue: "<b>'To set aside'</b>",                  question: [{prompt: "<b>'To set aside'</b>",                    name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "budget",       word1: "abandon",  word2: "forget",       word3: "store",        word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "allocate"      },
    {cue: "<b>'Insulate'</b>",                      question: [{prompt: "<b>'Insulate'</b>",                        name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "cancer",       word1: "walls",    word2: "isolate",      word3: "foam",         word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "asbestos"      },
    {cue: "<b>'Holds drinks'</b>",                  question: [{prompt: "<b>'Holds drinks'</b>",                    name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "bottle",       word1: "mug",      word2: "coaster",      word3: "cup",          word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "decanter"      },
    {cue: "<b>'To exhaust something'</b>",          question: [{prompt: "<b>'To exhaust something'</b>",            name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "expend",       word1: "exercise", word2: "tire",         word3: "discharge",    word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "deplete"       },
    {cue: "<b>'Hold at a certain temperature'</b>", question: [{prompt: "<b>'Hold at a certain temperature'</b>",   name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "nest",         word1: "fridge",   word2: "oven",         word3: "cook",         word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "incubate"      },
    {cue: "<b>'To set in motion'</b>",              question: [{prompt: "<b>'To set in motion'</b>",                name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "provoke",      word1: "roll",     word2: "throw",        word3: "commence",     word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "instigate"     },
    {cue: "<b>'Something you throw'</b>",           question: [{prompt: "<b>'Something you throw'</b>",             name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "spear",        word1: "ball",     word2: "rock",         word3: "punches",      word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "javelin"       },
    {cue: "<b>'Plant-based material'</b>",          question: [{prompt: "<b>'Plant-based material'</b>",            name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "sheets",       word1: "wicker",   word2: "table",        word3: "paper",        word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "linen"         },
    {cue: "<b>'Related to navigating'</b>",         question: [{prompt: "<b>'Related to navigating'</b>",           name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "sailing",      word1: "landmark", word2: "gps",          word3: "road",         word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "sextant"       },
    {cue: "<b>'A type of fee'</b>",                 question: [{prompt: "<b>'A type of fee'</b>",                   name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "tax",          word1: "parking",  word2: "reservation",  word3: "interest",     word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "tariff"        },
    {cue: "<b>'Causes a sedative effect'</b>",      question: [{prompt: "<b>'Causes a sedative effect'</b>",        name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "depressant",   word1: "fatigue",  word2: "tea",          word3: "nap",          word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "tranquilizer"  }
];

//data0: {"type": "associate", "target":"abdicate"   },  data1: {"type": "foil", "target":"abdicate"},        data2: {"type": "foil", "target":"abdicate"},      data3: {"type": "foil", "target":"abdicate"},    
//data0: {"type": "associate", "target":"allocate"   },  data1: {"type": "foil", "target":"allocate"},        data2: {"type": "foil", "target":"allocate"},      data3: {"type": "foil", "target":"allocate"},    
//data0: {"type": "associate", "target":"asbestos"   },  data1: {"type": "foil", "target":"asbestos"},        data2: {"type": "foil", "target":"asbestos"},      data3: {"type": "foil", "target":"asbestos"},    
//data0: {"type": "associate", "target":"decanter"   },  data1: {"type": "foil", "target":"decanter"},        data2: {"type": "foil", "target":"decanter"},      data3: {"type": "foil", "target":"decanter"},    
//data0: {"type": "associate", "target":"deplete"    },  data1: {"type": "foil", "target":"deplete"},         data2: {"type": "foil", "target":"deplete"},       data3: {"type": "foil", "target":"deplete"},     
//data0: {"type": "associate", "target":"incubate"   },  data1: {"type": "foil", "target":"incubate"},        data2: {"type": "foil", "target":"incubate"},      data3: {"type": "foil", "target":"incubate"},    
//data0: {"type": "associate", "target":"instigate"  },  data1: {"type": "foil", "target":"instigate"},       data2: {"type": "foil", "target":"instigate"},     data3: {"type": "foil", "target":"instigate"},   
//data0: {"type": "associate", "target":"javelin"    },  data1: {"type": "foil", "target":"javelin"},         data2: {"type": "foil", "target":"javelin"},       data3: {"type": "foil", "target":"javelin"},     
//data0: {"type": "associate", "target":"linen"      },  data1: {"type": "foil", "target":"linen"},           data2: {"type": "foil", "target":"linen"},         data3: {"type": "foil", "target":"linen"},       
//data0: {"type": "associate", "target":"sextant"    },  data1: {"type": "foil", "target":"sextant"},         data2: {"type": "foil", "target":"sextant"},       data3: {"type": "foil", "target":"sextant"},     
//data0: {"type": "associate", "target":"tariff"     },  data1: {"type": "foil", "target":"tariff"},          data2: {"type": "foil", "target":"tariff"},        data3: {"type": "foil", "target":"tariff"},      
//data0: {"type": "associate", "target":"tranquilizer"}, data1: {"type": "foil", "target":"tranquilizer"},    data2: {"type": "foil", "target":"tranquilizer"},  data3: {"type": "foil", "target":"tranquilizer"},
