// Test Phase Stimuli
var testwords = [
    {cue: "<font size='+2'><b>'Abandon a position'</b></font>",            question: [{prompt: "<font size='+1'><b>'Abandon a position'</b></font>",              name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "<font size='+2'>renounce</font>",     word1: "<font size='+2'>retreat</font>",  word2: "<font size='+2'>travel</font>",       word3: "<font size='+2'>yield</font>",        word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "<font size='+3'>abdicate</font>"    },
    {cue: "<font size='+2'><b>'To set aside'</b></font>",                  question: [{prompt: "<font size='+1'><b>'To set aside'</b></font>",                    name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "<font size='+2'>budget</font>",       word1: "<font size='+2'>abandon</font>",  word2: "<font size='+2'>forget</font>",       word3: "<font size='+2'>store</font>",        word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "<font size='+3'>allocate</font>"    },
    {cue: "<font size='+2'><b>'Insulate'</b></font>",                      question: [{prompt: "<font size='+1'><b>'Insulate'</b></font>",                        name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "<font size='+2'>cancer</font>",       word1: "<font size='+2'>walls</font>",    word2: "<font size='+2'>isolate</font>",      word3: "<font size='+2'>foam</font>",         word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "<font size='+3'>asbestos</font>"    },
    {cue: "<font size='+2'><b>'Holds drinks'</b></font>",                  question: [{prompt: "<font size='+1'><b>'Holds drinks'</b></font>",                    name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "<font size='+2'>bottle</font>",       word1: "<font size='+2'>mug</font>",      word2: "<font size='+2'>coaster</font>",      word3: "<font size='+2'>cup</font>",          word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "<font size='+3'>decanter</font>"    },
    {cue: "<font size='+2'><b>'To exhaust something'</b></font>",          question: [{prompt: "<font size='+1'><b>'To exhaust something'</b></font>",            name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "<font size='+2'>expend</font>",       word1: "<font size='+2'>exercise</font>", word2: "<font size='+2'>tire</font>",         word3: "<font size='+2'>discharge</font>",    word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "<font size='+3'>deplete</font>"     },
    {cue: "<font size='+2'><b>'Hold at a certain temperature'</b></font>", question: [{prompt: "<font size='+1'><b>'Hold at a certain temperature'</b></font>",   name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "<font size='+2'>nest</font>",         word1: "<font size='+2'>fridge</font>",   word2: "<font size='+2'>oven</font>",         word3: "<font size='+2'>cook</font>",         word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "<font size='+3'>incubate</font>"    },
    {cue: "<font size='+2'><b>'To set in motion'</b></font>",              question: [{prompt: "<font size='+1'><b>'To set in motion'</b></font>",                name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "<font size='+2'>provoke</font>",      word1: "<font size='+2'>roll</font>",     word2: "<font size='+2'>throw</font>",        word3: "<font size='+2'>commence</font>",     word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "<font size='+3'>instigate</font>"   },
    {cue: "<font size='+2'><b>'Something you throw'</b></font>",           question: [{prompt: "<font size='+1'><b>'Something you throw'</b></font>",             name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "<font size='+2'>spear</font>",        word1: "<font size='+2'>ball</font>",     word2: "<font size='+2'>rock</font>",         word3: "<font size='+2'>punches</font>",      word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "<font size='+3'>javelin</font>"     },
    {cue: "<font size='+2'><b>'Plant-based material'</b></font>",          question: [{prompt: "<font size='+1'><b>'Plant-based material'</b></font>",            name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "<font size='+2'>sheets</font>",       word1: "<font size='+2'>wicker</font>",   word2: "<font size='+2'>table</font>",        word3: "<font size='+2'>paper</font>",        word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "<font size='+3'>linen</font>"       },
    {cue: "<font size='+2'><b>'Related to navigating'</b></font>",         question: [{prompt: "<font size='+1'><b>'Related to navigating'</b></font>",           name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "<font size='+2'>sailing</font>",      word1: "<font size='+2'>landmark</font>", word2: "<font size='+2'>gps</font>",          word3: "<font size='+2'>road</font>",         word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "<font size='+3'>sextant</font>"     },
    {cue: "<font size='+2'><b>'A type of fee'</b></font>",                 question: [{prompt: "<font size='+1'><b>'A type of fee'</b></font>",                   name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "<font size='+2'>tax</font>",          word1: "<font size='+2'>parking</font>",  word2: "<font size='+2'>reservation</font>",  word3: "<font size='+2'>interest</font>",     word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "<font size='+3'>tariff</font>"      },
    {cue: "<font size='+2'><b>'Causes a sedative effect'</b></font>",      question: [{prompt: "<font size='+1'><b>'Causes a sedative effect'</b></font>",        name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "<font size='+2'>depressant</font>",   word1: "<font size='+2'>fatigue</font>",  word2: "<font size='+2'>tea</font>",          word3: "<font size='+2'>nap</font>",          word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "<font size='+3'>tranquilizer</font>"}
];
/*
var testwords_1 = [
    {cue: "<font size='+2'><b>'To set aside'</b></font>",                  question: [{prompt: "<font size='+1'><b>'To set aside'</b></font>",                    name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "<font size='+2'>budget</font>",       word1: "<font size='+2'>abandon</font>",  word2: "<font size='+2'>forget</font>",       word3: "<font size='+2'>store</font>",        word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "allocate"      },
    {cue: "<font size='+2'><b>'Holds drinks'</b></font>",                  question: [{prompt: "<font size='+1'><b>'Holds drinks'</b></font>",                    name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "<font size='+2'>bottle</font>",       word1: "<font size='+2'>mug</font>",      word2: "<font size='+2'>coaster</font>",      word3: "<font size='+2'>cup</font>",          word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "decanter"      },
    {cue: "<font size='+2'><b>'To exhaust something'</b></font>",          question: [{prompt: "<font size='+1'><b>'To exhaust something'</b></font>",            name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "<font size='+2'>expend</font>",       word1: "<font size='+2'>exercise</font>", word2: "<font size='+2'>tire</font>",         word3: "<font size='+2'>discharge</font>",    word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "deplete"       },
    {cue: "<font size='+2'><b>'Plant-based material'</b></font>",          question: [{prompt: "<font size='+1'><b>'Plant-based material'</b></font>",            name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "<font size='+2'>sheets</font>",       word1: "<font size='+2'>wicker</font>",   word2: "<font size='+2'>table</font>",        word3: "<font size='+2'>paper</font>",        word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "linen"         },
    {cue: "<font size='+2'><b>'Related to navigating'</b></font>",         question: [{prompt: "<font size='+1'><b>'Related to navigating'</b></font>",           name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "<font size='+2'>sailing</font>",      word1: "<font size='+2'>landmark</font>", word2: "<font size='+2'>gps</font>",          word3: "<font size='+2'>road</font>",         word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "sextant"       },
    {cue: "<font size='+2'><b>'Causes a sedative effect'</b></font>",      question: [{prompt: "<font size='+1'><b>'Causes a sedative effect'</b></font>",        name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "<font size='+2'>depressant</font>",   word1: "<font size='+2'>fatigue</font>",  word2: "<font size='+2'>tea</font>",          word3: "<font size='+2'>nap</font>",          word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "tranquilizer"  },
];

var testwords_2 = [
    {cue: "<font size='+2'><b>'Abandon a position'</b></font>",            question: [{prompt: "<font size='+1'><b>'Abandon a position'</b></font>",              name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "<font size='+2'>renounce</font>",     word1: "<font size='+2'>retreat</font>",  word2: "<font size='+2'>travel</font>",       word3: "<font size='+2'>yield</font>",        word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "abdicate"      },
    {cue: "<font size='+2'><b>'Insulate'</b></font>",                      question: [{prompt: "<font size='+1'><b>'Insulate'</b></font>",                        name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "<font size='+2'>cancer</font>",       word1: "<font size='+2'>walls</font>",    word2: "<font size='+2'>isolate</font>",      word3: "<font size='+2'>foam</font>",         word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "asbestos"      },
    {cue: "<font size='+2'><b>'Hold at a certain temperature'</b></font>", question: [{prompt: "<font size='+1'><b>'Hold at a certain temperature'</b></font>",   name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "<font size='+2'>nest</font>",         word1: "<font size='+2'>fridge</font>",   word2: "<font size='+2'>oven</font>",         word3: "<font size='+2'>cook</font>",         word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "incubate"      },
    {cue: "<font size='+2'><b>'To set in motion'</b></font>",              question: [{prompt: "<font size='+1'><b>'To set in motion'</b></font>",                name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "<font size='+2'>provoke</font>",      word1: "<font size='+2'>roll</font>",     word2: "<font size='+2'>throw</font>",        word3: "<font size='+2'>commence</font>",     word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "instigate"     },
    {cue: "<font size='+2'><b>'Something you throw'</b></font>",           question: [{prompt: "<font size='+1'><b>'Something you throw'</b></font>",             name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "<font size='+2'>spear</font>",        word1: "<font size='+2'>ball</font>",     word2: "<font size='+2'>rock</font>",         word3: "<font size='+2'>punches</font>",      word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "javelin"       },
    {cue: "<font size='+2'><b>'A type of fee'</b></font>",                 question: [{prompt: "<font size='+1'><b>'A type of fee'</b></font>",                   name: 'recalled_word',   value: "", required: false, rows: 1, columns: 25}],    word0: "<font size='+2'>tax</font>",          word1: "<font size='+2'>parking</font>",  word2: "<font size='+2'>reservation</font>",  word3: "<font size='+2'>interest</font>",     word0_type: "associate", word1_type: "foil1", word2_type: "foil2", word3_type: "foil3", target: "tariff"        },
];
*/